name: Terraform Destroy Azure Resources

on:
  workflow_run:
    workflows: ["Terraform Azure WebApp CI/CD"]
    types:
      - completed

jobs:
  terraform:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Wait 10 minutes before destroy
        run: sleep 200  # 600 seconds = 10 mins

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Terraform state
        uses: actions/download-artifact@v4
        with:
          name: terraform-state
          path: terraform-artifacts/

      - name: Authenticate with Azure OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: terraform-artifacts