name: Terraform Destroy Azure Resources

on:

  workflow_run:
    branches:
      - main      
    workflows: ["Terraform Azure WebApp CI/CD"]
    types:
      - completed

jobs:
  # This job will run only if the previous workflow run was successful
  # and the branch is 'main'  
  
  terraform:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }} 
    steps:
      - name: Check if the workflow run was successful
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo "Previous workflow run was successful, proceeding with destroy."
      - name: Sleep for 10 seconds
        run: sleep 300
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Download Terraform state
        uses: actions/download-artifact@v4
        with:
          name: terraform-state

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve